<?php
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use \module\core\component\GridRangeFilter;
?>

<div class="page-title">
    Manage Go Tour
</div>

<?php
$gridColumns = [
    [
        'attribute'=>'id',
        'options'=>[
            'width'=>'80px',
            'class'=>'text-center'
        ],
        'contentOptions'=>[
            'class'=>'text-center'
        ]
    ],
    [
        'attribute'=>'list_no',
        'format'=>'raw'
    ],
    [
        'attribute'=>'user_id',
        'value'=>function($m){
            if(! $m->user) return 'Unkonw';

            $phone = $m->user->getProfile()->phone_number;
            return '['.$m->user->username.'/'.$phone.'] '.$m->user->email;
        }
    ],
    [
        'attribute'=>'date_start'
    ],
    [
        'attribute'=>'date_end'
    ],
    [
        'attribute'=>'status',
        'value'=>function($m){
            return $m->getStatusName();
        }
    ],
    [
       'class' => 'yii\grid\ActionColumn',
       'header' => 'Action', 
       'template' => '{confirm}',
       'buttons'=>[
            'confirm'=>function($url, $model){
                return Html::a('<span class="glyphicon glyphicon-earphone"></span>', $url, [
                    'title' => Yii::t('yii', 'Confirm'),
                    'data-confirm' => Yii::t('yii', 'Are you sure to confirm this item?'),
                    'data-method' => 'post']);
            }
       ],
       'headerOptions' => ['width' => '20'],
       'contentOptions'=>[
            'align'=>'center'
       ]
    ],
];

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
    'emptyCell'=>'&nbsp;'
]);
?>