<div class="page-title">
    议表盘
</div>

<div class="panel panel-default">
    <div class="panel-heading">今日任务</div>
    <div class="panel-body">
        暂无...
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">最近日志</div>
    <div class="panel-body">
        暂无...
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading">新用户</div>
    <div class="panel-body">
        暂无...
    </div>
</div>