<style type="text/css">
.seo-meta-types{margin:0;padding:15px 0;border-bottom:solid 1px #ddd;}
.seo-meta-types > li{
    display:inline-block;
    list-style-type:none;
    margin:0 5px 5px 0;
}
.seo-meta-types > li > a{
    display:block;
    padding:5px 10px;
    border:solid 1px #ddd;
    border-radius:4px;
    text-decoration:none;
}
.seo-meta-types > li:hover > a {
    color:#f90;
    border-color:#f90;
}
.seo-meta-types > li.seo-meta-types:hover > a, .seo-meta-types > li.active > a{
    background: #f90;
    color: #fff;
    border: solid 1px #fff;
}

.seo-variables {padding:15px 0;}

.seo-meta-page {margin-top:5px;}
.seo-meta-page .field-item{margin-bottom:15px;border-radius:4px;padding:15px;background:#f2f2f2;}
.seo-meta-page .field-item .label-control{display:block;margin-bottom:15px;text-transform:uppercase;;color:#333;}
.seo-meta-page .field-item .label-control:after{content:':';}
.seo-meta-page .field-item .form-control{
    width:100%;margin-bottom:5px;
    border-radius:2px;
    height: 28px;
    line-height: 24px;
    padding: 3px;
    box-shadow: none;
    border-color: #ddd;
    color:#333;
}
</style>

<ul class="seo-meta-types">
    <?php foreach($configs as $path => $item):?>
        <li class="<?php echo $path === $currentPath ? 'active' : ''?>">
            <a href="<?php echo \yii\helpers\Url::current(['path' => $path, 'area' => $area])?>"><?php echo $item['name']?></a>
        </li>
    <?php endforeach?>
</ul>

<?php if ($currentPath):?>
    <template id="seo-editor">
        <div class="seo-variables">
            <?php if(isset($configs[$currentPath]['variables'])):?>
                <span style="color:#777">Variables:</span> <?php echo $configs[$currentPath]['variables']?>
            <?php endif?>
        </div>
        <div class="seo-meta-page">
            <div class="field-item field-title">
              <label class="label-control">Title</label>
              <input v-model="data.title[0]" class="form-control" placeholder="Default">
              <input v-model="data.title[1]" class="form-control" placeholder="Chinese">
            </div>
            <div class="field-item field-keywords">
              <label class="label-control">Keywords</label>
              <input v-model="data.keywords[0]" class="form-control" placeholder="Default">
              <input v-model="data.keywords[1]" class="form-control" placeholder="Chinese">
            </div>
            <div class="field-item field-description">
              <label class="label-control">Description</label>
              <input v-model="data.description[0]" class="form-control" placeholder="Default">
              <input v-model="data.description[1]" class="form-control" placeholder="Chinese">
            </div>
        </div>
        <div class="actions">
            <button @click="submit" class="btn btn-primary">提交</button>
        </div>
    </template>

    <script>
    new Vue({
        el: '#seo-editor',
        data: {
            data: <?php echo json_encode($entity)?>
        },
        methods: {
            submit: function () {
                var csrf = '<?php echo \WS::$app->getRequest()->getCsrfToken()?>';
                $.post('<?php echo \yii\helpers\Url::current()?>', {data: this.data, _csrf: csrf}, function (res) {
                    window.location.reload();
                });
            }
        }
    });
    </script>
<?php endif?>
