<?php $this->beginContent('@module/page/views/layouts/base.phtml'); ?>
    <div id="header" class="ui-bar">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="/">米乐居</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown <?php $this->activeMenuItem('system-setting')?>">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">System <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="<?php echo $this->createUrl(['configurtion/setting/index'])?>">Configuration</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">addy.lee@gmail.com <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li role="separator" class="divider"></li>
                                <li><a href="<?php echo $this->createUrl(['user/account/logout'])?>">Logout</a></li>
                            </ul>
                        </li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>
    </div><!--end header-->

    <style type="text/css">
    .left-menu-bar h2.group {
        font-size: 13px;
        background: #f0f0f0;
        padding: 3px 8px;
        margin-right: 15px;
        margin-bottom: 4px;
        border-radius: 0 0 10px 4px;
        color: #888;
    }
    </style>

    <div class="container-fluid" >
    <div id="main" style="display:table;width:100%;">
        <div style="display:table-row">
            <div class="left-menu-bar" style="display:table-cell;width:190px;vertical-align:top;">
                <h2 class="group">HOUSE</h2>
                <ul>
                    <li class="<?php $this->activeMenuItem('rets-go-tour')?>">
                        <a href="<?php echo $this->createUrl(['rets/go-tour/index'])?>">Go Tour</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('rets-view-template')?>">
                        <a href="<?php echo $this->createUrl(['rets/view-template-editor/show'])?>">View Template(MA)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('rets-view-template2')?>">
                        <a href="<?php echo $this->createUrl(['rets/view-template-editor/listhub-show'])?>">View Template(Listhub)</a>
                    </li>
                </ul>
                <h2 class="group">NEWS</h2>
                <ul>
                    <li class="<?php $this->activeMenuItem('news')?>">
                        <a href="<?php echo $this->createUrl(['/news/default/index'])?>">News List</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('categories-3')?>">
                        <a href="<?php echo $this->createUrl(['/category/default/index', 'taxonomyId'=>3])?>">Categories</a>
                    </li>
                </ul>
                <h2 class="group">YELLOWPAGE</h2>
                <ul>
                    <li class="<?php $this->activeMenuItem('yellowpages-ma')?>">
                        <a href="<?php echo $this->createUrl(['yellowpage/yellowpage/index', 'area_id'=>'ma'])?>">Items(for MA)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('yellowpages-ny')?>">
                        <a href="<?php echo $this->createUrl(['yellowpage/yellowpage/index', 'area_id'=>'ny'])?>">Items(for NY)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('yellowpages-ga')?>">
                        <a href="<?php echo $this->createUrl(['yellowpage/yellowpage/index', 'area_id'=>'ga'])?>">Items(for GA)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('yellowpages-il')?>">
                        <a href="<?php echo $this->createUrl(['yellowpage/yellowpage/index', 'area_id'=>'il'])?>">Items(for IL)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('yellowpages-dc')?>">
                        <a href="<?php echo $this->createUrl(['yellowpage/yellowpage/index', 'area_id'=>'ca'])?>">Items(for CA)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('categories-2')?>">
                        <a href="<?php echo $this->createUrl(['/category/default/index', 'taxonomyId'=>2])?>">Categories</a>
                    </li>
                </ul>
                <h2 class="group">SCHOOL DISTRICT</h2>
                <ul>
                    <li class="<?php $this->activeMenuItem('schooldistrict')?>">
                        <a href="<?php echo $this->createUrl(['schooldistrict/schooldistrict/index'])?>">School Districtss</a>
                    </li>
                </ul>
                <h2 class="group">SEO (Only PC)</h2>
                <ul>
                    <li class="<?php $this->activeMenuItem('seo-ma')?>">
                        <a href="<?php echo $this->createUrl(['page/seo/index', 'area' => 'ma'])?>">Page Settings (for MA)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('seo-ny')?>">
                        <a href="<?php echo $this->createUrl(['page/seo/index', 'area' => 'ny'])?>">Page Settings (for NY)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('seo-ga')?>">
                        <a href="<?php echo $this->createUrl(['page/seo/index', 'area' => 'ga'])?>">Page Settings (for GA)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('seo-ca')?>">
                        <a href="<?php echo $this->createUrl(['page/seo/index', 'area' => 'ca'])?>">Page Settings (for CA)</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('seo-il')?>">
                        <a href="<?php echo $this->createUrl(['page/seo/index', 'area' => 'il'])?>">Page Settings (for IL)</a>
                    </li>
                </ul>
                <h2 class="group">Configurtions</h2>
                <ul>
                    <li class="<?php $this->activeMenuItem('setting-general-global')?>">
                        <a href="<?php echo $this->createUrl(['configurtion/setting/index', 'area_id'=>'global'])?>">General for Global</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('setting-general-ma')?>">
                        <a href="<?php echo $this->createUrl(['configurtion/setting/index', 'area_id'=>'ma'])?>">Settings for MA</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('setting-general-ny')?>">
                        <a href="<?php echo $this->createUrl(['configurtion/setting/index', 'area_id'=>'ny'])?>">Settings for NY</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('setting-general-ga')?>">
                        <a href="<?php echo $this->createUrl(['configurtion/setting/index', 'area_id'=>'ga'])?>">Settings for GA</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('setting-general-il')?>">
                        <a href="<?php echo $this->createUrl(['configurtion/setting/index', 'area_id'=>'il'])?>">Settings for IL</a>
                    </li>
                    <li class="<?php $this->activeMenuItem('setting-general-dc')?>">
                        <a href="<?php echo $this->createUrl(['configurtion/setting/index', 'area_id'=>'ca'])?>">Settings for CA</a>
                    </li>
                </ul>
            </div>
            <div class="content" style="display:table-cell;vertical-align:top;">
                <?php foreach (Yii::$app->session->getAllFlashes() as $key => $message) { ?>
                    <div class="alert alert-<?=$key?>" role="alert"><?=$message?></div>
                <?php } ?>
                
                <?php echo $content;?>
            </div>
        </div>
    </div> <!--end main-->
    </div>
<?php $this->endContent()?>

<script>
(function($){
    var layoutInit = function() {
        $('#main').height($(window).innerHeight() - $('#header').outerHeight() - 20);
    };
    layoutInit();
    $(window).on('resize', function(){
        layoutInit();
    });
})(jQuery);
</script>
<style>
.left-menu-bar .active a{color:#f90;font-weight:bold;}
</style>