<?php
use yii\grid\GridView;
use yii\helpers\Html;
use yii\helpers\Url;
use \module\core\component\GridRangeFilter;
?>

<div class="page-title">
    Manage News
    <div class="toolbar">
        <?php echo Html::a(
                            '<span class="glyphicon glyphicon-plus"></span> New', 
                            \WS::$app->urlManager->createUrl('news/default/edit'),
                            ['class'=>'btn btn-primary','name' =>'submit-button']
                        ) ?>
    </div>
</div>

<?php
$typeNames = \common\core\TaxonomyTerm::typeOptions(3);
$gridColumns = [
    [
        'attribute'=>'id',
        'options'=>[
            'width'=>'80px',
            'class'=>'text-center'
        ],
        'contentOptions'=>[
            'class'=>'text-center'
        ]
    ],
    [
        'attribute'=>'title',
        'header'=>'Name'
    ],
    [
        'attribute'=>'type_id',
        'value'=>function($m) use($typeNames){
            if (isset($typeNames[$m->type_id])) {
                return $typeNames[$m->type_id];
            }
            return 'Unknown';
        },
        'options'=>[
            'width'=>'120px'
        ],
        'contentOptions'=>[
            'class'=>'text-center'
        ],
        'header'=>'Type',
        'filter'=>$typeNames
    ],
    [
        'attribute'=>'created_at',
        'options'=>[
            'width'=>'120px'
        ],
        'header'=>'Create Time'
    ],
    [
        'attribute'=>'status',
        'options'=>[
            'width'=>'70px'
        ],
        'filter'=>['0'=>'No Publish', '1'=>'Published'],
        'value'=>function($m){
            if ($m->status === 0) {
                return 'No Publish';
            } elseif ($m->status === 1)
                return 'Published';
            elseif ($m->status === 2)
                return 'Waiting';
        },
        'contentOptions'=>[
            'class'=>'text-center'
        ],
    ],
    [
        'class' => 'yii\grid\ActionColumn',
        'header'=>'Action',
        'buttons'=>[
            'view'=>function(){return '';},
            'delete'=>function(){return '';}
        ],
        'urlCreator' => function ($action, $m, $key, $index) {
            if ($action === 'update') {
                if ($m->status === 2) return 'javascript:alert("正在编译中，稍候! 刷新查看最新状态...");';
                return Url::toRoute(['/news/default/edit', 'id'=>$m->id]);
            }
        },
        'options'=>[
            'width'=>'30px'
        ],
        'contentOptions'=>[
            'class'=>'text-center'
        ]
    ],
];

echo GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
    'emptyCell'=>'&nbsp;'
]);
?>