<div class="sd-grid">
  <table class="table" style="width:auto;max-width:100%">
    <thead>
      <tr>
        <th colspan="2">ITEM</th>
        <th>CITY IDS</th>
        <th>ACTIONS</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach($items as $item):?>
        <?php $json = json_decode($item['json']);?>
      <tr>
        <td>
          <img style="width:90px" src="<?php echo \WS::$app->params['media']['baseUrl'].'/school-area/images/'.$item['image'].'.jpg'?>"/>
          <br/>
          #<?php echo $item['id']?> / <?php echo $item['code']?>
        </td>
        <td><?php echo implode('/', $json->name)?></td>
        <td><?php echo $item['city_id']?></td>
        <td>
          <a href="/index.php?r=schooldistrict/schooldistrict/edit&id=<?php echo $item['id']?>">
            <span class="glyphicon glyphicon-pencil"></span>
          </a>
        </td>
      </tr>
      <?php endforeach?>
    </tbody>
  </table>
</div>
<div style="margin-top:5px;">
<input value="" placeholder="新编码" id="input-new-code"/><a id="btn-new" class="btn btn-default" style="margin-left:4px;">新增</a>
</div>

<script type="text/javascript">
(function($){
	$('#btn-new').click(function() {
		var newCode = $('#input-new-code').val();
		if(newCode.trim() === '') {
			$('#input-new-code').focus();
			return;
		}
		window.location.href = '/index.php?r=schooldistrict/schooldistrict/edit&code='+newCode;
	});
})(jQuery);
</script>

<style>
.sd-grid .btn-remove {
	cursor: pointer;
    display: none;
    padding: 2px;
    font-size: 12px;
    height: 16px;
    line-height: 10px;
    background: #337ab7;
    color: #fff;
    border: solid 1px #fff;
}
</style>