<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$_options = ['position'=>$this::POS_HEAD, 'depends' => '\module\page\assets\Base'];

$_cm = 'https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.39.2';
$this->registerJsFile("{$_cm}/codemirror.min.js", $_options);
$this->registerJsFile("{$_cm}/mode/xml/xml.min.js", $_options);
$this->registerJsFile("{$_cm}/addon/edit/closetag.min.js", $_options);
$this->registerJsFile("{$_cm}/addon/fold/foldcode.min.js", $_options);
$this->registerCssFile("{$_cm}/codemirror.css", $_options);
?>

<style>
ul.types{list-style-type:none;margin:10px 0;padding:0;}
ul.types > li{display:inline-block;margin:0;padding:0;margin-right:7px;}
ul.types > li > a{display:block;padding:3px 20px;background:#ececec;}
ul.types > li.active > a{background:#f90;color:#fff;}

.field-viewtemplateeditorform-content > label{display:none;}
.field-viewtemplateeditorform-content .col-sm-6{width:0%;}
.field-viewtemplateeditorform-content .help-block{background:#f7f7f7;padding:5px;margin:0;border-top:#eee solid 1px;}
.control-label.col-sm-3{display:none;}
.col-sm-6{width:100% !important;}
.CodeMirror {
  height:700px;
}
</style>

<?php
$form = ActiveForm::begin([
    'method'=>'post',
    'layout' => 'horizontal',
    'options' => [
        'class'=>'form-horizontal',
        'enctype' => 'multipart/form-data' 
    ]
    ]);
?>

<div class="page-title">
    View Template Editor
    <div class="toolbar">
        <?php echo Html::submitButton('<span class="glyphicon glyphicon-ok-circle"></span> Save', ['class'=>'btn btn-primary','name' =>'submit-button']) ?>   
        <?php echo Html::resetButton('<span class="glyphicon glyphicon-repeat"></span> Reset', ['class'=>'btn','name' =>'submit-button']) ?>
    </div>
</div>

<ul class="types">
    <?php foreach(['rn', 'sf', 'mf', 'cc', 'ci', 'bu', 'ld'] as $code):?>
        <li class="<?php echo $currentType == $code ? 'active' : ''?>"><a href="<?php echo $this->createUrl(['rets/view-template-editor/show', 'type'=>$code])?>"><?php echo strtoupper($code)?></a></li>
    <?php endforeach?>
</ul>

<div style="border-top: 1px solid #cecece; border-bottom: 1px solid #cecece;">
    <?php echo $form->field($model, 'xml_rules')->textArea(['id'=>'code', 'rows'=>'40', 'cols'=>'120']) ?>
</div>
<?php ActiveForm::end(); ?>

<script>
    function isFullScreen(cm) {
      return /\bCodeMirror-fullscreen\b/.test(cm.getWrapperElement().className);
    }
    function winHeight() {
      return window.innerHeight || (document.documentElement || document.body).clientHeight;
    }
    function setFullScreen(cm, full) {
      var wrap = cm.getWrapperElement(), scroll = cm.getScrollerElement();
      if (full) {
        wrap.className += " CodeMirror-fullscreen";
        scroll.style.height = (winHeight() - 180) + "px";
        document.documentElement.style.overflow = "hidden";
      } else {
        wrap.className = wrap.className.replace(" CodeMirror-fullscreen", "");
        scroll.style.height = "";
        document.documentElement.style.overflow = "";
      }
      cm.refresh();
    }

  var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
    mode: {name: "xml", alignCDATA: true},
    lineNumbers: true,
    htmlMode: false,
    indentWithTabs: true,
    autofocus: true,
    implicitlyClosed:{'rn':true, 'sf':true, 'mf':true, 'cc':true, 'ci':true, 'bu':true, 'ld':true,'group':true,'fields':true},
    contextGrabbers:{'title':true,'prefix':true,'suffix':true},
    extraKeys: {
        "'>'": function(cm) { cm.closeTag(cm, '>'); },
        "'/'": function(cm) { cm.closeTag(cm, '/'); },
        "F11": function(cm) {
          setFullScreen(cm, !isFullScreen(cm));
        },
        "Esc": function(cm) {
          setFullScreen(cm, !isFullScreen(cm));
          //if (isFullScreen(cm)) setFullScreen(cm, false);
        }
    },
    wordWrap: true,
    lineWrapping: true,
    onGutterClick: CodeMirror.newFoldFunction(CodeMirror.braceRangeFinder)
  });
  setFullScreen(editor, true);
</script>

